# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_name', models.CharField(max_length=30)),
                ('supply_remaining', models.IntegerField(default=0)),
                ('supply_total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='supplies_quantity',
        ),
        migrations.AddField(
            model_name='supplydetail',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.Reservation'),
        ),
        migrations.AddField(
            model_name='supplydetail',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_of', to='meetings.Supply'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='supplies',
            field=models.ManyToManyField(to='meetings.Supply'),
        ),
    ]
