# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-27 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20170827_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reservation_of', to='meetings.MeetingRoom'),
            preserve_default=False,
        ),
    ]
