# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-27 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_reservation_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='reservation_status',
            field=models.CharField(choices=[('ND', 'No Disponible'), ('D', 'Disponible'), ('R', 'Reservada'), ('C', 'Confirmada')], default='D', max_length=30),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='supplies',
            field=models.ManyToManyField(default='default_supplies', to='meetings.Supply'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_remaining',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_total',
            field=models.IntegerField(default=1),
        ),
    ]
