# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-27 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20170827_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='supplies',
            field=models.ManyToManyField(default=meetings.models.MeetingRoom.default_supplies, to='meetings.Supply'),
        ),
    ]
