# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-28 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20170828_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='from_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='to_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
